#!/bin/sh
# -*- mode: sh; -*-

$HOME/.config/bspwm/panel &

bspc config border_width       2
bspc config window_gap         5

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Screenkey manage=off

sxhkd &
