#!/bin/sh

#-----------------------------------------------------------------------------
PANEL_FIFO="$HOME/.config/bspwm/panfifo"
PANEL_HEIGHT="16"
PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"

#-----------------------------------------------------------------------------
COLOR_FOREGROUND='#FFA3A6AB'
COLOR_BACKGROUND='#FF34322E'
COLOR_ACTIVE_MONITOR_FG='#FF34322E'
COLOR_ACTIVE_MONITOR_BG='#FF58C5F1'
COLOR_INACTIVE_MONITOR_FG='#FF58C5F1'
COLOR_INACTIVE_MONITOR_BG='#FF34322E'
COLOR_FOCUSED_OCCUPIED_FG='#FFF6F9FF'
COLOR_FOCUSED_OCCUPIED_BG='#FF5C5955'
COLOR_FOCUSED_FREE_FG='#FFF6F9FF'
COLOR_FOCUSED_FREE_BG='#FF6D561C'
COLOR_FOCUSED_URGENT_FG='#FF34322E'
COLOR_FOCUSED_URGENT_BG='#FFF9A299'
COLOR_OCCUPIED_FG='#FFA3A6AB'
COLOR_OCCUPIED_BG='#FF34322E'
COLOR_FREE_FG='#FF6F7277'
COLOR_FREE_BG='#FF34322E'
COLOR_URGENT_FG='#FFF9A299'
COLOR_URGENT_BG='#FF34322E'
COLOR_LAYOUT_FG='#FFA3A6AB'
COLOR_LAYOUT_BG='#FF34322E'
COLOR_TITLE_FG='#FFA3A6AB'
COLOR_TITLE_BG='#FF34322E'
COLOR_STATUS_FG='#FFA3A6AB'
COLOR_STATUS_BG='#FF34322E'

#-----------------------------------------------------------------------------
while [ $(pgrep -cx panel) -gt 1 ]; do
  pkill -ox -9 panel
done

killall -9 stalonetray
killall -9 xtitle
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

if [ -e "$PANEL_FIFO" ]; then
  rm "$PANEL_FIFO"
fi
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &


#-----------------------------------------------------------------------------
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &


#-----------------------------------------------------------------------------
panel_bar () {
  num_mon=$(bspc query -M | wc -l)

  while read -r line ; do
	case $line in
	  S*)
		# clock output
		sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
		;;
	  T*)
		# xtitle output
		title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
		;;
	  W*)
		# bspwm internal state
		wm_infos=""
		IFS=':'
		set -- ${line#?}
		while [ $# -gt 0 ] ; do
		  item=$1
		  name=${item#?}
		  case $item in
			M*)
			  # active monitor
			  if [ $num_mon -gt 1 ] ; then
				wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
			  fi
			  ;;
			m*)
			  # inactive monitor
			  if [ $num_mon -gt 1 ] ; then
				wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
			  fi
			  ;;
			O*)
			  # focused occupied desktop
			  wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
			  ;;
			F*)
			  # focused free desktop
			  wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
			  ;;
			U*)
			  # focused urgent desktop
			  wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
			  ;;
			o*)
			  # occupied desktop
			  wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}"
			  ;;
			f*)
			  # free desktop
			  wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}"
			  ;;
			u*)
			  # urgent desktop
			  wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
			  ;;
			L*)
			  # layout
			  wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
			  ;;
		  esac
		  shift
		done
		;;
	esac
	printf "%s\n" "%{l}${wm_infos}%{c}${title}%{r}${sys_infos}"
  done
}

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
