URLS  =
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_ack
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_ag
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_cmake
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_cpanm
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_dzen2
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_fab
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_gem
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_ghc
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_gradle
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_httpie
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_jq
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_lein
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_manage.py
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_mvn
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_ps
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_nl
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_pygmentize
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_setup.py
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_socat
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_virtualbox
URLS += https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_zsh

fetch:
	@for url in $(URLS); do \
		curl -sOL $$url ; \
	done
