# -*- mode: sh -*- 
# .zshenv

export PATH="$HOME/.local/bin:$PATH"

# preferred tools
export EDITOR="vim"
#export PAGER="vimpager"
export PAGER="less"
export BROWSER="firefox"


# tool options
export GREP_OPTIONS="--color=auto"
export GREP_COLOR="1;32" #green
export WORKON_HOME=~/.virtualenvs
export PIP_DOWNLOAD_CACHE=~/.pip/download-cache
export TERM=xterm-256color

# misc options
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# program options
export DOTREMINDERS="$HOME/org/reminders"

# go
export GOROOT="$HOME/.local/go"
export GOPATH="$HOME/source/go"

fpath=(~/.zfunc $fpath)
typeset -U fpath

path=(\
  $HOME/bin \
  $HOME/.local/bin \
  $HOME/.luarocks/bin \
  $HOME/.cabal/bin \
  $HOME/.dotfiles/bin \
  $HOME/.dotfiles/util-co/bin \
  $HOME/.local/go/bin \
  $GOROOT/bin \
  /usr/pgsql-9.3/bin/ \
  /opt/nodejs/bin/ \
  /opt/mathematica/bin/ \
  $path )
typeset -U path

[[ -f $HOME/.zshenv.local ]] && . $HOME/.zshenv.local
