# -*- mode: sh -*-

#-----------------------------------------------------------------------------
# preferred programs
export EDITOR="vim"
export PAGER="less"
# (( $+commands[most] ))    && export PAGER="most"
(( $+commands[firefox] )) && export BROWSER="firefox"

#-----------------------------------------------------------------------------
# pager config
if [[ "$PAGER" = "less" ]]; then
  export LESS="-egiMXRF"
  export LESSCHARSET="utf-8"
fi

#-----------------------------------------------------------------------------
# system program options
export GREP_OPTIONS="--color=auto"
export GREP_COLOR="1;32" #green
export PIP_DOWNLOAD_CACHE="$HOME/.pip/download-cache"
export TERM=xterm-256color

#-----------------------------------------------------------------------------
# user program options
export DOTREMINDERS="$HOME/org/reminders"

#-----------------------------------------------------------------------------
# programming environment options
# golang
export GOPATH="$HOME/.local/go"

# perl locallib
export PERL_LOCAL_LIB_ROOT="/home/gv/.perl5"
export PERL_MB_OPT="--install_base /home/gv/.perl5"
export PERL_MM_OPT="INSTALL_BASE=/home/gv/.perl5"
export PERL5LIB="/home/gv/.perl5/lib/perl5/x86_64-linux-thread-multi:/home/gv/.perl5/lib/perl5"
export PATH="/home/gv/perl5/bin:$PATH"

#-----------------------------------------------------------------------------
# zsh load path
fpath=(\
  $HOME/.zfunc/
  $HOME/.zfunc/completions/
  $fpath)
typeset -U fpath

#-----------------------------------------------------------------------------
# path
path=(\
  $HOME/bin \
  $HOME/.local/bin \
  $HOME/.dotfiles/bin \
  $HOME/.dotfiles/bin/3rdparty \
  $HOME/.luarocks/bin \
  $HOME/.perl5/bin \
  $HOME/.cabal/bin \
  $GOPATH/bin \
  $path )
typeset -U path

#-----------------------------------------------------------------------------
umask 007

#-----------------------------------------------------------------------------
# local config
[[ -f $HOME/.zshenv.local ]] && . $HOME/.zshenv.local
