# aliases
alias ls="ls --color=auto -F --group-directories-first"
alias ll="ls -lsh"
alias lla="ll -ld *(-/DN)"

alias h='history'
alias f='find | grep'

alias c="clear"

alias   ..='cd ..'
alias cd..='cd ..'
alias cd...='cd ../../'
alias cd....='cd ../../../'
alias gcd='cd $(git rev-parse --show-toplevel)'

alias d='dirs -v'
alias g='git'
alias v='vim'
alias g='gvim'
alias gt='gvim --remote-tab'
alias _='sudo'

alias gvimt='gvim --remote-tab'
alias cdiff='colordiff'
alias agi='sudo apt-get install'
alias ayi='sudo yum install'
alias ays='sudo yum search'
alias jobs='jobs -l'
alias tree='tree -F -C'
#alias ack='ack-grep'

alias nautilus="nautilus --no-desktop"
alias pyclean='rm **/*.(pyc|pyo)'
alias ctags="ctags --fields=+l --c-kinds=+p --c++-kinds=+p"

# global/suffix aliases
alias -s zip='zipinfo'
alias -g G='|& egrep -i'
alias -g EG='|& egrep '
alias -g EH='|& head '
alias -g ET='|& tail -15 '
alias -g WC='| wc -l'
alias -g DN='/dev/null'


# history
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000

setopt share_history
setopt histignoredups

setopt hist_verify
setopt inc_append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_space


# directories
DIRSTACKSIZE=10
#setopt auto_name_dirs
setopt auto_pushd
setopt pushd_ignore_dups
setopt autocd


# key bindings
bindkey -e # emacs mode
bindkey "\e[1~" beginning-of-line    # Home
bindkey "\e[4~" end-of-line          # End
bindkey "\e[5~" beginning-of-history # PageUp
bindkey "\e[6~" end-of-history       # PageDown
bindkey "\e[2~" quoted-insert        # Ins
bindkey "\e[3~" delete-char          # Del
bindkey "\e[5C" forward-word
bindkey "\eOc" emacs-forward-word
bindkey "\e[5D" backward-word
bindkey "\eOd" emacs-backward-word
bindkey "\e\e[C" forward-word
bindkey "\e\e[D" backward-word
bindkey "\e[Z" reverse-menu-complete # Shift+Tab
# for rxvt
bindkey "\e[7~" beginning-of-line # Home
bindkey "\e[8~" end-of-line       # End
# for non RH/Debian xterm, can't hurt for RH/Debian xterm
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
# for freebsd console
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line

# misc
WORDCHARS='*?_[]~&;!#$%^(){}<>'

unsetopt beep
#setopt printexitvalue
setopt interactivecomments
setopt notify
setopt long_list_jobs
setopt zle


# completion
zstyle :compinstall filename '/home/gv/.zshrc'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
autoload -Uz compinit
compinit


# limits
limit stack        8192
limit descriptors  1024
limit coredumpsize 0
limit -s


# prompt
autoload -Uz colors
autoload -Uz promptinit
setopt promptsubst
colors
promptinit
prompt mine red yellow vc:0


## need to figure out a way to set these from within prompt setup ...
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions

precmd_functions+='vcs_repo_precmd_hook'
preexec_functions+='vcs_repo_preexec_hook'
chpwd_functions+='vcs_repo_chpwd_hook'


for s (~/.zfunc/*.zsh(x)) source $s
[[ -f $HOME/.zshrc.local ]] && . $HOME/.zshrc.local
